mybatis:
  mapper-locations: classpath:mapping/*.xml
server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: abcdef
    url: jdbc:mysql://127.0.0.1:3306/more_flow_app?serverTimezone=UTC&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root